export const PILLARS = [
  {
    id: "locksmithing",
    num: "01",
    title: "Locksmithing & Security",
    tag: "Digital Immunity",
    img: "https://media.base44.com/images/public/6a6890ed0920bc884c73a76a/c9180e468_generated_46057bd3.png",
    accent: "cyan",
    intro: "When it comes to vehicle security, we manipulate the core data — not just the door lock.",
    long:
      "From a complete all-keys-lost situation to a deadlocked anti-theft system, we restore access at the data level. We laser-cut and program keys from scratch, clone fried modules, read raw chip data off the board, and emulate failed steering locks. If your Immobilizer has locked you out, we bypass it — not by guessing, but by reading and rewriting the security code the vehicle trusts.",
    points: [
      "Complete Key Generation (All Keys Lost) — precision laser cutting & programming from zero keys",
      "Immobilizer (IMMO) Systems & Anti-Theft Lockouts — bypass, reset, reprogram deadlocked systems",
      "Module Cloning & Virginizing — extract hex data from fried ECU/BCM, write to used modules or wipe to factory state",
      "EEPROM & MCU Microchip Programming — desolder chips, read raw board data, modify & flash back",
      "ESL/ELV Steering Lock Emulation & Repair — bypass failed electronic steering column locks",
      "Smart Keys, Proximity Fobs & Transponders — match rolling codes for push-to-start systems",
    ],
    subservices: [
      {
        name: "Complete Key Generation (All Keys Lost)",
        summary: "Precision laser cutting & programming from zero keys.",
        detail: `When every key is gone we don't guess the cuts. We decode the physical lock (door/ignition/trunk graft) or pull the Immobilizer PIN through the OBD2 port, then read the EEPROM/MCU on the IMMO or BCM to derive the secret key transponder codes. A fresh blade is laser-cut on our code-cutting machine and the transponder/remote is matched to the rolling-code seed so the car treats it as original equipment.`,
        tools: ["Key cutting machine (Silca / Advanced Diagnostics)", "EEPROM reader (X-Prog / UPA-USB)", "J2534 pass-thru dongle", "IMMO programmer (VVDI / Autel IM508)", "Transponder cloner"],
      },
      {
        name: "Immobilizer (IMMO) Systems & Anti-Theft Lockouts",
        summary: "Bypass, reset and reprogram deadlocked security systems.",
        detail: `A dead 12V battery, a replaced ECU, or a lockout after a failed start can deadlock the immobilizer so no key will catch. We read the seed/PIN the IMMO expects, re-synchronize the transponder list, reset the handshake counter, and restore the trust relationship between BCM, ECU and key — without a dealer tow.`,
        tools: ["OBD-II IMMO interface", "EEPROM/MCU reader", "VIN/PIN retrieval service", "J2534 pass-thru"],
      },
      {
        name: "Module Cloning & Virginizing",
        summary: "Extract hex from a fried module; write it to a used one or wipe to factory.",
        detail: `Your original ECU or BCM is burnt, flooded or bricked. Instead of a dealer-only virgin part, we pull the immobilizer and configuration data off the dead module's EEPROM/flash, then write that hex onto a donor module — so it powers up as the car's original. Going the other way, we "virginize" a used module: wipe its previous VIN/IMMO pairing so it accepts re-pairing into your vehicle.`,
        tools: ["EEPROM/flash reader-writer (X-Prog, Orange5)", "Hot-air rework station", "Bench flash harness", "Module cloning suite"],
      },
      {
        name: "EEPROM & MCU Microchip Programming",
        summary: "Desolder chips, read the raw board data, modify and flash back.",
        detail: `When a failure traces to a single chip, we go to the silicon. We desolder the EEPROM/MCU (clamped or hot-air), dump its raw hex, edit the relevant bytes (mileage, IMMO flag, VIN, calibration), then flash the corrected image back and reflow the chip in place. This is board-level work most locksmiths and shops refuse to touch.`,
        tools: ["SOIC/DFN desoldering & reflow", "Universal programmer", "Logic analyzer", "Hex editor & checksum tooling"],
      },
      {
        name: "ESL / ELV Steering Lock Emulation & Repair",
        summary: "Bypass failed electronic steering column locks.",
        detail: `The electronic steering lock (ESL/ELV) is a known failure point on Mercedes and other push-to-start vehicles — when it seizes, the wheel stays locked and the car won't power on. We rebuild the lock motor/gear or, when repair isn't viable, install an emulation module that tells the system the column is unlocked, restoring driveability without the brittle mechanical part.`,
        tools: ["ESL/ELV emulator", "IR/solder bench", "Motor & gear service kit"],
      },
      {
        name: "Smart Keys, Proximity Fobs & Transponders",
        summary: "Match rolling codes for push-to-start systems.",
        detail: `Push-to-start and proximity (PEPS) systems use rolling-code protocols that change on every handshake. We register new fobs into the car's security list, sync the rolling-code seed, and program the unlock/trunk/panic buttons — handling both fixed-code transponders and crypto/rolling-code chips across domestic, European and Asian platforms.`,
        tools: ["Proximity key programmer", "RF signal tester", "Rolling-code sync tool"],
      },
    ],
    process: [
      { title: "Authorization & VIN pull", desc: "We confirm ownership/authorization and pull the VIN, IMMO architecture and model-specific access path." },
      { title: "Read the trust data", desc: "OBD2 PIN retrieval, or bench-read the EEPROM/MCU on the IMMO/BCM/ESL for the seed and transponder list." },
      { title: "Cut & match", desc: "Laser-cut the blade and program the transponder/remote to the car's rolling-code seed." },
      { title: "Validate", desc: "Start/run cycle test, confirm lock/unlock and that the IMMO stays synchronized across power cycles." },
      { title: "Clean diagnostic trail", desc: "Clear learned-key logs and fault codes so the system reports as original equipment." },
    ],
    symptoms: [
      "All keys are lost or stolen",
      "Car cranks but the immobilizer light flashes — anti-theft lockout",
      "Replaced the ECU or BCM and now the car won't recognize any key",
      "Steering wheel stays locked on a push-to-start vehicle",
      "Key fob works to unlock but the engine won't start",
    ],
    faqs: [
      { q: "Do you need the original key?", a: "No. All-keys-lost is our specialty — we derive what we need from the lock and the immobilizer data." },
      { q: "Will a cloned used module start my car?", a: "Yes — we transfer the immobilizer and configuration hex so the donor module boots as your car's original." },
      { q: "Can you delete the steering lock entirely?", a: "Yes, with an emulation module for vehicles where that's the supported repair path." },
    ],
  },
  {
    id: "electrical",
    num: "02",
    title: "Electrical & Data Networks",
    tag: "Rolling Server Room",
    img: "https://media.base44.com/images/public/6a6890ed0920bc884c73a76a/f69670e3c_generated_d8453c26.png",
    accent: "cyan",
    intro: "While others guess, we use data, oscilloscopes, and factory software to pinpoint the exact failure in copper and code.",
    long:
      "Modern cars are rolling networks. We diagnose CAN, LIN and FlexRay buses with oscilloscope signal analysis, trace parasitic draws by fuse voltage-drop, flash factory calibrations through J2534 pass-thru, and rebuild melted harnesses to OEM spec. We also recalibrate ADAS — radar cruise, lane-keep and blind-spot — and reset SRS/airbag modules after a crash.",
    points: [
      "J2534 Pass-Thru Programming — flash factory calibrations (Ford FJDS, GM SPS, Techstream)",
      "CAN Bus, LIN Bus & FlexRay Diagnostics — trace network failures with oscilloscope signal analysis",
      "Parasitic Draw & Short-to-Ground Tracing — isolate phantom drains via fuse voltage-drop testing",
      "Custom Wiring Harness Repair — repin connectors, rebuild melted harnesses, OEM weather-pack & Tesa tape",
      "ADAS Recalibration — calibrate radar cruise, lane-departure cameras, blind-spot monitors",
      "Complete SRS/Airbag Systems — crash-data diagnosis, clock spring & impact sensor replacement, module reset",
    ],
    subservices: [
      {
        name: "J2534 Pass-Thru Programming",
        summary: "Flash factory calibrations through OEM software.",
        detail: `We connect a J2534 pass-thru device to the OBD2 port and use the manufacturer's own software (Ford FJDS, GM SPS, Toyota Techstream, etc.) to flash the latest factory calibration, reprogram a replacement module, or clear a brick — without a dealer visit. We handle authentication, seed/key security access and the full flash/seed sequence correctly.`,
        tools: ["J2534 pass-thru interface", "OEM software subscriptions", "Stable bench power supply", "Factory calibration files"],
      },
      {
        name: "CAN, LIN & FlexRay Diagnostics",
        summary: "Trace network failures with oscilloscope signal analysis.",
        detail: `Most "dead module" complaints are network problems, not part failures. We probe CAN-H/CAN-L, LIN and FlexRay with an oscilloscope to read the actual bit stream — finding a shorted termination, a silent node, a corrupted frame or a ground shift that a scan tool can't see. We isolate the fault to a specific connector or splice, not the entire bus.`,
        tools: ["Automotive oscilloscope", "CAN bus analyzer", "Breakout box", "Differential probes"],
      },
      {
        name: "Parasitic Draw & Short-to-Ground Tracing",
        summary: "Isolate phantom drains via fuse voltage-drop testing.",
        detail: `A battery that goes dead overnight isn't always a bad battery. We measure the voltage-drop across every fuse to quantify current draw without breaking the circuit, then walk the offending branch to the exact module or shorted wire — resolving phantom drains that strand vehicles and frustrate other shops.`,
        tools: ["Millivolt drop tester", "Current clamp", "Fuse pull & probe kit", "Thermal imaging"],
      },
      {
        name: "Custom Wiring Harness Repair",
        summary: "Repin connectors, rebuild melted harnesses to OEM spec.",
        detail: `A melted harness from a high-current failure or rodent chew doesn't require a full engine harness from the dealer. We repin individual terminals, splice in OEM-spec wire and weather-pack connectors, re-wrap with Tesa cloth tape, and route to factory clips — preserving the original routing, twist-pairs and shielding so the network stays clean.`,
        tools: ["OEM terminal crimp/de-pin kit", "Weather-pack connectors", "Solder/heat-shrink splice", "Tesa cloth harness tape"],
      },
      {
        name: "ADAS Recalibration",
        summary: "Calibrate radar cruise, lane-keep and blind-spot systems.",
        detail: `After a windshield, bumper, module, sensor or even an alignment change, ADAS must be recalibrated or it can false-trigger or miss a target. We perform both static (target-board) and dynamic (driven) calibration for radar cruise, lane-departure cameras and blind-spot monitors to OEM aim points.`,
        tools: ["Static target boards / pattern mat", "Calibration laser jig", "ADAS scan tool", "Dynamic drive route"],
      },
      {
        name: "SRS / Airbag Systems",
        summary: "Crash-data diagnosis, sensor & clock-spring repair, module reset.",
        detail: `After a deployment or a stored crash code, we diagnose the SRS network, replace the clock spring and impact sensors as needed, and reset or replace the airbag module so the light clears legitimately — not just switched off. We verify the full deployment loop reads healthy before the car leaves.`,
        tools: ["SRS diagnostic scan tool", "Clock spring & sensor inventory", "Module reset bench", "Deployment-loop validator"],
      },
    ],
    process: [
      { title: "Scan & scope", desc: "Full module scan plus oscilloscope capture of the affected bus or signal." },
      { title: "Isolate the fault", desc: "Voltage-drop walk, pin-level resistance and frame analysis to the exact node." },
      { title: "Repair or reflash", desc: "Repin/harness repair, module reprogram via J2534, or sensor replacement." },
      { title: "Calibrate", desc: "ADAS static/dynamic aim and SRS deployment-loop validation as needed." },
      { title: "Verify", desc: "Final scan clears every controller; confirm no pending codes across a run cycle." },
    ],
    symptoms: [
      "Multiple modules drop offline or 'not communicating' intermittently",
      "Battery dies overnight with everything off",
      "Check-engine or airbag light after a flash, swap or minor collision",
      "Cruise or lane-keep disabled after a windshield or bumper replacement",
      "Melted, rubbed-through or chewed wiring near the engine or trunk",
    ],
    faqs: [
      { q: "Can you flash modules at your shop?", a: "Yes — J2534 pass-thru plus OEM software lets us program without the dealer." },
      { q: "My scan tool says 'no comms' — is the module dead?", a: "Often not. We scope the bus first and frequently trace it to a wiring or termination fault." },
      { q: "Do you recalibrate ADAS after a windshield?", a: "Yes — static target and dynamic calibration for radar, camera and blind-spot systems." },
    ],
  },
  {
    id: "performance",
    num: "03",
    title: "Performance Tuning",
    tag: "Horsepower Fluent",
    img: "https://media.base44.com/images/public/6a6890ed0920bc884c73a76a/8d0087281_generated_6e7ee0c8.png",
    accent: "heat",
    intro: "We don't just fix cars — we make them faster and optimize how they run. For those who speak the language of horsepower.",
    long:
      "From a flash tune to a full stand-alone engine management swap, we dial in fuel maps, ignition timing and boost for real power — and we prove it on the datalog, not the butt-dyno. Wideband integration, TCU tuning, and off-road deletes for track-built cars. We speak the language of horsepower fluently.",
    points: [
      "ECU Remapping & Flashing — modify fuel maps, ignition timing, boost parameters for max power & efficiency",
      "Stand-Alone Engine Management — wire & configure Holley, Haltech, Megasquirt for swaps and custom builds",
      "TCU (Transmission Control Unit) Tuning — adjust shift points, line pressures, torque limiters for firmer shifts",
      "Deletes & Bypasses — program out speed/rev limiters, bypass factory sensors for track-built cars (off-road use)",
      "Datalogging & Wideband Integration — read real-time data under load to dial in air/fuel ratio, prevent knock",
    ],
    subservices: [
      {
        name: "ECU Remapping & Flashing",
        summary: "Modify fuel, timing and boost maps for real power and efficiency.",
        detail: `We read the ECU's calibration, edit the fuel and ignition tables, boost control and torque limits, then flash a custom tune matched to your hardware (intake, exhaust, turbo, fuel). Every change is validated against a wideband datalog under load — not a generic off-the-shelf file — so the tune is safe at your altitude, fuel and boost.`,
        tools: ["ECU read/write tool (PCMFlash, KESS, Autotuner)", "Dyno & wideband datalog", "Calibration editor", "Knock detection"],
      },
      {
        name: "Stand-Alone Engine Management",
        summary: "Wire & configure Holley, Haltech, Megasquirt for swaps & builds.",
        detail: `Engine swaps and custom builds often run best on a standalone ECU. We wire the harness, configure the base map, set up triggers, injectors and sensors, and dial the car in from crank to WOT — supporting Holley, Haltech, Megasquirt and MaxxECU platforms.`,
        tools: ["Standalone ECU & harness", "Trigger/sensor setup kit", "Dyno & wideband", "Calibration software"],
      },
      {
        name: "TCU (Transmission Control) Tuning",
        summary: "Shift points, line pressure and torque limits for firmer shifts.",
        detail: `The transmission is half the tune. We adjust shift points, line pressure, torque-limit timing and lock-up behavior so shifts hold power instead of soft-cutting it — improving both ET and drivability on automatics and dual-clutches.`,
        tools: ["TCU flash tool", "Clutch-pressure log", "Drivability datalog"],
      },
      {
        name: "Deletes & Bypasses (off-road / track)",
        summary: "Remove speed & rev limiters; bypass factory sensors for track builds.",
        detail: `For track-only vehicles we program out speed and rev limiters, de-prioritize emissions monitors, and bypass factory sensors that conflict with the build. We're explicit: these tunes are for off-road, closed-course use and we won't ship them for street emmissions compliance.`,
        tools: ["Calibration editor", "Off-road delete files", "Closed-course validation log"],
      },
      {
        name: "Datalogging & Wideband Integration",
        summary: "Real-time data under load to dial in AFR and prevent knock.",
        detail: `Tuning without a datalog is guessing. We log wideband AFR, knock, EGT, boost and trims under load — repeatedly — and revise the map until it's clean across the RPM and load range. We'll send you the logs so you can see exactly why each change was made.`,
        tools: ["Wideband O2", "Datalogger", "Knock & EGT probes", "Boost reference"],
      },
    ],
    process: [
      { title: "Hardware review", desc: "Confirm intake/exhaust/turbo/fuel match the tune goal before touching the map." },
      { title: "Read & baseline", desc: "Pull the stock calibration and log a baseline run with the wideband." },
      { title: "Edit the map", desc: "Adjust fuel, timing, boost and torque limits to your hardware and fuel." },
      { title: "Tune under load", desc: "Iterate on the datalog until AFR, knock and trims are clean across the range." },
      { title: "Deliver & document", desc: "Flash the final tune, hand you the logs, and note what to watch for going forward." },
    ],
    symptoms: [
      "Bought a generic tuner file and the car runs worse or pings",
      "Big turbo/intake mods but no tune to match the airflow",
      "Transmission soft-cuts power at the top of each shift",
      "Engine swap needs a standalone ECU wired and dialed in",
      "Track car needs limiters removed and a closed-course tune",
    ],
    faqs: [
      { q: "Do you guarantee a horsepower number?", a: "We tune to a safe, validated datalog; the dyno confirms the gain rather than promising a number." },
      { q: "Can you tune my standalone swap?", a: "Yes — Holley, Haltech, Megasquirt and MaxxECU from wiring to full calibration." },
      { q: "Are delete tunes street legal?", a: "No — deletes are off-road / closed-course only and we won't ship them for compliance use." },
    ],
  },
  {
    id: "mechanical",
    num: "04",
    title: "Mechanical & Powertrain",
    tag: "Heavy Metal Grit",
    img: "https://media.base44.com/images/public/6a6890ed0920bc884c73a76a/aae62aaf0_generated_51d34c82.png",
    accent: "data",
    intro: "We aren't just a laptop guy. We have the heavy tools and the grit to rip a car to bare chassis and build it back up.",
    long:
      "We have the heavy tools and the grit to tear a car down to a bare chassis and rebuild it. Engine swaps, head and valvetrain work, transmission and drivetrain rebuilds, forced-induction plumbing, suspension and big-brake kits, fuel and cooling systems. Code and copper are only half the car — the other half is iron, and we own both.",
    points: [
      "Engine Swaps & Complete Rebuilds — drop subframes, replace piston rings, main bearings, upgraded camshafts",
      "Cylinder Head & Valvetrain Repair — head gaskets, bent valves, timing chains, tensioners, precise cam timing",
      "Transmission & Drivetrain — swap autos/manuals, rebuild clutch packs, install LSDs, heavy-duty axles & driveshafts",
      "Forced Induction Plumbing — install turbo/superchargers, tap oil pans, mount intercoolers",
      "Suspension, Steering & Braking — coilovers, polyurethane bushings, steering racks, big brake kits, stainless lines",
      "Fuel & Cooling Systems — high-flow pumps & injectors, water pumps, heater cores, mechanical overheating diagnosis",
    ],
    subservices: [
      {
        name: "Engine Swaps & Complete Rebuilds",
        summary: "Drop subframes; rings, bearings, upgraded cams in-house.",
        detail: `From a direct-fit engine swap to a full blueprint rebuild, we pull the subframe, refresh pistons/rings, main and rod bearings, head gaskets and upgraded camshafts — measuring clearances to spec rather than just replacing parts. We handle mounts, sensors and ECU pairing so the swap runs like it belonged there.`,
        tools: ["Engine hoist & subframe drop rig", "Bore gauge & micrometer kit", "Balance & torque spec sheets", "Cam/crank timing tools"],
      },
      {
        name: "Cylinder Head & Valvetrain",
        summary: "Gaskets, bent valves, timing chains — timed precisely.",
        detail: `A slipped timing chain or over-rev bent-valves incident doesn't mean a junk engine. We reface or replace the head, seat fresh valves and guides, replace chains/tensioners and time the cam precisely — with VVT calibration verified against a scope so the phasing is exactly where it should be.`,
        tools: ["Valve spring compressor", "Head surface & valve seat machine", "Cam timing & VVT locking kit", "Vacuum leak tester"],
      },
      {
        name: "Transmission & Drivetrain",
        summary: "Auto/manual swaps, clutch packs, LSDs, heavy-duty axles.",
        detail: `We swap autos for manuals (and back), rebuild clutch packs and valves, install limited-slip diffs, and upgrade to heavy-duty axles and driveshafts for big-torque builds. TCU setup and launch calibration are paired with the mechanical work so the box behaves as well as it's built.`,
        tools: ["Trans rebuild bench", "Dial-indicator setup gauges", "Press & bearing puller", "Shim & preload kit"],
      },
      {
        name: "Forced Induction Plumbing",
        summary: "Turbo/supercharger install, oil-pan taps, intercooler mounts.",
        detail: `Adding boost is as much plumbing as it is tuning. We mount turbos/superchargers, tap the oil pan for drain and feed, route charge piping, mount intercoolers and run boost reference lines — then tune the result to match (see Performance).`,
        tools: ["Oil-pan drill/tap rig", "Charge piping & bead-roller", "Intercooler mount kit", "Oil feed/drain fittings"],
      },
      {
        name: "Suspension, Steering & Braking",
        summary: "Coilovers, poly bushings, racks, big brake kits, steel lines.",
        detail: `Handling and stopping are part of the build. We install coilovers, polyurethane bushings, steering racks, big-brake kits and stainless lines — and align the result so it actually corners. Heavy-torque builds get the upgraded axles to match.`,
        tools: ["Spring compressor", "Press & bushing driver set", "Hunter-grade alignment ref", "Brake line bending/flaring kit"],
      },
      {
        name: "Fuel & Cooling Systems",
        summary: "High-flow pumps/injectors, water pumps, overheating diagnosis.",
        detail: `Fuel and cooling keep the tune alive. We spec high-flow pumps and injectors, replace water pumps and heater cores, and mechanically diagnose overheating (thermostat, water pump, head gasket, radiator, fan) rather than guessing "bad thermostat" and sending you out.`,
        tools: ["Injector flow-test bench", "Coolant pressure tester", "Combustion-leak detector", "Flow-rated pump/injector inventory"],
      },
    ],
    process: [
      { title: "Teardown & inspect", desc: "Strip to the needed level, measure clearances and document what's actually worn." },
      { title: "Parts & machine", desc: "Machine/replace failed components; spec upgraded parts to the build goal." },
      { title: "Reassemble to spec", desc: "Rebuild with verified torque, preload and timing — not feel." },
      { title: "Pair to electronics", desc: "ECU/TCU/sensor setup so the fresh mechanicals run correctly." },
      { title: "Test & break-in", desc: "Run-in, leak-down, alignment and a final road/dyno verification." },
    ],
    symptoms: [
      "Engine knock, low compression or burning oil",
      "Slipping transmission or a swap you want done with handling",
      "Overheating that keeps coming back after the thermostat swap",
      "Timing-chain rattle or a bent-valve over-rev event",
      "Adding boost and need the plumbing and tune done right",
    ],
    faqs: [
      { q: "Do you do engine swaps?", a: "Yes — direct-fit swaps and blueprint rebuilds, mounts, sensors and ECU pairing included." },
      { q: "Can you do the tune after the mechanical build?", a: "Yes — mechanical, electrical and tuning under one roof, so the build is consistent." },
      { q: "Do you diagnose overheating mechanically?", a: "Yes — thermostat, pump, head gasket, radiator and fan are all checked, not assumed." },
    ],
  },
];